# Generated by Django 6.0.4 on 2026-05-22 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Incapacitado', 'Incapacitado'), ('Suspendido', 'Suspendido')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Exportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=255)),
                ('pais', models.CharField(default='Sin producto', max_length=255)),
                ('fecha_envio', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], max_length=20)),
                ('producto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('ttelefono', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Supervisor', 'Supervisor')], max_length=20)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Incapacitado', 'Incapacitado'), ('Suspendido', 'Suspendido')], max_length=20)),
                ('horario_fijo', models.CharField(blank=True, choices=[('Mañana 6:00am - 2:00pm', 'Mañana 6:00am - 2:00pm'), ('Tarde 2:00pm - 10:00pm', 'Tarde 2:00pm - 10:00pm')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, max_length=255, null=True)),
                ('ingredientes', models.CharField(max_length=255)),
                ('cantidad_requerida', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_entrega', models.DateField()),
                ('fecha_limite', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Cancelado', 'Cancelado'), ('Finalizado', 'Finalizado')], max_length=20)),
                ('empleado_responsable', models.ForeignKey(db_column='empleado_responsable', on_delete=django.db.models.deletion.CASCADE, to='myApp.empleado')),
                ('creado_por', models.ForeignKey(db_column='creado_por', on_delete=django.db.models.deletion.CASCADE, to='myApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=100, unique=True)),
                ('cantidad', models.CharField(max_length=255)),
                ('fecha_produccion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('exportacion', models.ForeignKey(db_column='exportacion_id', on_delete=django.db.models.deletion.CASCADE, to='myApp.exportacion')),
                ('produccion', models.ForeignKey(db_column='produccion_id', on_delete=django.db.models.deletion.CASCADE, to='myApp.produccion')),
            ],
        ),
        migrations.AddField(
            model_name='exportacion',
            name='produccion',
            field=models.ForeignKey(blank=True, db_column='produccion_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.produccion'),
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(choices=[('Mañana 6:00am - 2:00pm', 'Mañana 6:00am - 2:00pm'), ('Tarde 2:00pm - 10:00pm', 'Tarde 2:00pm - 10:00pm')], max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(db_column='creado_por', on_delete=django.db.models.deletion.CASCADE, related_name='turnos_creados', to='myApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.empleado')),
                ('turno_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turno_actual', to='myApp.turno')),
                ('turno_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turno_solicitado', to='myApp.turno')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='creado_por',
            field=models.ForeignKey(db_column='creado_por', on_delete=django.db.models.deletion.CASCADE, to='myApp.usuario'),
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('tipo_reporte', models.CharField(choices=[('Diario', 'Diario'), ('Semanal', 'Semanal')], max_length=20)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Enviado', 'Enviado'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Borrador', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('unidades_producidas', models.CharField(blank=True, max_length=255, null=True)),
                ('unidades_pendientes', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_revision', models.DateField(blank=True, null=True)),
                ('observacion_admin', models.TextField(blank=True, null=True)),
                ('produccion', models.ForeignKey(blank=True, db_column='produccion_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.produccion')),
                ('revisado_por', models.ForeignKey(blank=True, db_column='revisado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_revisadas', to='myApp.usuario')),
                ('supervisor', models.ForeignKey(db_column='supervisor_id', on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras_creadas', to='myApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(max_length=255)),
                ('fecha_asignacion', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=20)),
                ('empleado', models.ForeignKey(db_column='empleado_id', on_delete=django.db.models.deletion.CASCADE, to='myApp.empleado')),
                ('turno', models.ForeignKey(db_column='turno_id', on_delete=django.db.models.deletion.CASCADE, to='myApp.turno')),
                ('asignado_por', models.ForeignKey(db_column='asignado_por', on_delete=django.db.models.deletion.CASCADE, to='myApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RotacionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('semana', models.IntegerField()),
                ('estado', models.CharField(choices=[('Asignado', 'Asignado'), ('Completado', 'Completado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=20)),
                ('sabado_asignado', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.empleado')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.turno')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('empleado', 'fecha_inicio', 'fecha_fin'), name='unique_turno_semanal')],
            },
        ),
    ]
