# Generated by Django 6.0.4 on 2026-06-02 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacora',
            name='revisado_por',
        ),
        migrations.RemoveField(
            model_name='exportacion',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='revisado_por',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ttelefono',
        ),
    ]
