# Generated by Django 6.0.4 on 2026-05-16 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_novedad', models.CharField(choices=[('Observación general', 'Observación general'), ('Incidencia en proceso', 'Incidencia en proceso'), ('Ajuste de cantidad', 'Ajuste de cantidad'), ('Cambio de estado', 'Cambio de estado'), ('Nota de calidad', 'Nota de calidad')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('produccion', models.ForeignKey(db_column='produccion_id', on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='myApp.produccion')),
                ('registrado_por', models.ForeignKey(db_column='registrado_por', on_delete=django.db.models.deletion.CASCADE, related_name='bitacora_entries', to='myApp.usuario')),
            ],
            options={
                'verbose_name': 'Entrada de bitácora',
                'verbose_name_plural': 'Bitácora de producción',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
