# Generated by Django 6.0.4 on 2026-05-23 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='horario_fijo',
        ),
    ]
