# Generated by Django 4.2 on 2026-05-18 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_remove_usuario_telefono_usuario_ttelefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('tipo_reporte', models.CharField(choices=[('Diario', 'Diario'), ('Semanal', 'Semanal'), ('Mensual', 'Mensual')], max_length=20)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Enviado', 'Enviado'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Borrador', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('entregas_pendientes', models.IntegerField(default=0)),
                ('unidades_producidas', models.IntegerField(default=0)),
                ('fecha_revision', models.DateField(blank=True, null=True)),
                ('observacion_admin', models.TextField(blank=True, null=True)),
                ('produccion', models.ForeignKey(blank=True, db_column='produccion_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.produccion')),
                ('revisado_por', models.ForeignKey(blank=True, db_column='revisado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_revisadas', to='myApp.usuario')),
                ('supervisor', models.ForeignKey(db_column='supervisor_id', on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras_creadas', to='myApp.usuario')),
            ],
        ),
    ]
