# Generated by Django 6.0.4 on 2026-06-02 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_remove_bitacora_revisado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Reservado', 'Reservado'), ('Exportado', 'Exportado')], default='Disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='lote',
            name='exportacion',
            field=models.ForeignKey(blank=True, db_column='exportacion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.exportacion'),
        ),
    ]
