# Generated by Django 6.0.4 on 2026-06-05 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_lote_estado_alter_lote_exportacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='exportacion',
            field=models.ForeignKey(blank=True, db_column='exportacion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='myApp.exportacion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Incapacitado', 'Incapacitado'), ('Suspendido', 'Suspendido')], default='Activo', max_length=20),
        ),
    ]
