# Generated by Django 6.0.4 on 2026-05-21 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_bitacoraproduccion'),
        ('myApp', '0003_bitacora'),
    ]

    operations = [
    ]
