# Generated by Django 6.0.4 on 2026-06-05 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_lote_exportacion_alter_usuario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisores', to='myApp.turno'),
        ),
    ]
