# Generated by Django 6.0.4 on 2026-05-21 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_merge_0002_bitacoraproduccion_0003_bitacora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empturno',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='empturno',
            name='turno',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='entregas_pendientes',
        ),
        migrations.RemoveField(
            model_name='exportacion',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='produccion',
            name='cantidad_planificada',
        ),
        migrations.RemoveField(
            model_name='produccion',
            name='cantidad_producida',
        ),
        migrations.RemoveField(
            model_name='produccion',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='produccion',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='fecha',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='unidades_pendientes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='produccion',
            field=models.ForeignKey(blank=True, db_column='produccion_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.produccion'),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='producto',
            field=models.CharField(default='sin prodcuto', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produccion',
            name='cantidad_requerida',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='horario_fijo',
            field=models.CharField(blank=True, choices=[('Mañana 6:00am - 2:00pm', 'Mañana 6:00am - 2:00pm'), ('Tarde 2:00pm - 10:00pm', 'Tarde 2:00pm - 10:00pm')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='tipo_reporte',
            field=models.CharField(choices=[('Diario', 'Diario'), ('Semanal', 'Semanal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='unidades_producidas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exportacion',
            name='pais',
            field=models.CharField(default='Sin producto', max_length=255),
        ),
        migrations.AlterField(
            model_name='lote',
            name='cantidad',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='producto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='creado_por',
            field=models.ForeignKey(db_column='creado_por', on_delete=django.db.models.deletion.CASCADE, related_name='turnos_creados', to='myApp.usuario'),
        ),
        migrations.CreateModel(
            name='RotacionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('semana', models.IntegerField()),
                ('estado', models.CharField(choices=[('Asignado', 'Asignado'), ('Completado', 'Completado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=20)),
                ('sabado_asignado', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.empleado')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.turno')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.empleado')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.usuario')),
                ('turno_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turno_actual', to='myApp.turno')),
                ('turno_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turno_solicitado', to='myApp.turno')),
            ],
        ),
        migrations.DeleteModel(
            name='BitacoraProduccion',
        ),
        migrations.DeleteModel(
            name='EmpTurno',
        ),
        migrations.AddConstraint(
            model_name='rotacionturno',
            constraint=models.UniqueConstraint(fields=('empleado', 'fecha_inicio', 'fecha_fin'), name='unique_turno_semanal'),
        ),
    ]
