# Generated by Django 4.2 on 2026-05-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_rotacionturno_solicitud_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='ttelefono',
            new_name='telefono',
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='turno',
            name='horario',
            field=models.CharField(choices=[('Mañana 6:00am - 2:00pm', 'Mañana 6:00am - 2:00pm'), ('Tarde 2:00pm - 10:00pm', 'Tarde 2:00pm - 10:00pm')], max_length=50),
        ),
    ]
