# Generated by Django 6.0.4 on 2026-06-08 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_usuario_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='exportacion',
        ),
        migrations.AddField(
            model_name='exportacion',
            name='lote',
            field=models.ForeignKey(blank=True, db_column='lote_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.lote'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='produccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.produccion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Incapacitado', 'Incapacitado'), ('Suspendido', 'Suspendido')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='turno',
            field=models.CharField(blank=True, choices=[('Mañana 6:00am - 2:00pm', 'Mañana 6:00am - 2:00pm'), ('Tarde 2:00pm - 10:00pm', 'Tarde 2:00pm - 10:00pm')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='HistorialCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField(blank=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Enviado', 'Enviado'), ('Error', 'Error')], max_length=20)),
                ('error_detalle', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.empleado')),
            ],
        ),
    ]
