# Generated by Django 4.2 on 2026-06-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_rename_ttelefono_usuario_telefono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacora',
            name='revisado_por',
        ),
        migrations.RemoveField(
            model_name='exportacion',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='revisado_por',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='creado_por',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='descripcion_tarea',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='cantidad_cajas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='empresa_exportadora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='numero_contenedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='peso_caja',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='peso_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='unidades_por_caja',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='origen_cacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='unidad',
            field=models.CharField(blank=True, choices=[('Kilogramos', 'Kilogramos'), ('Gramos', 'Gramos')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rotacionturno',
            name='horario_sabado',
            field=models.CharField(blank=True, choices=[('Mañana 6:00am - 12:00pm', 'Mañana 6:00am - 12:00pm'), ('Tarde 12:00pm - 6:00pm', 'Tarde 12:00pm - 6:00pm')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='observacion_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='tarea',
            field=models.CharField(choices=[('Temperar', 'Temperar'), ('Mezclado', 'Mezclado'), ('Moldear', 'Moldear'), ('Desmoldear', 'Desmoldear'), ('Picar', 'Picar'), ('Triturado', 'Triturado'), ('Molienda', 'Molienda'), ('Paletear', 'Paletear'), ('Empacar', 'Empacar'), ('Sellado', 'Sellado'), ('Etiquetado', 'Etiquetado'), ('Limpieza General', 'Limpieza General'), ('Limpieza de Maquinaria', 'Limpieza de Maquinaria')], max_length=255),
        ),
    ]
