# Generated by Django 4.2 on 2026-06-05 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_remove_bitacora_revisado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='turno',
            field=models.CharField(choices=[('Mañana 6:00am - 2:00pm', 'Mañana 6:00am - 2:00pm'), ('Tarde 2:00pm - 10:00pm', 'Tarde 2:00pm - 10:00pm')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lote',
            name='exportacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.exportacion'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='produccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.produccion'),
        ),
    ]
