# Generated by Django 4.2 on 2026-06-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_usuario_turno_alter_lote_exportacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='turno',
            field=models.CharField(blank=True, choices=[('Mañana 6:00am - 2:00pm', 'Mañana 6:00am - 2:00pm'), ('Tarde 2:00pm - 10:00pm', 'Tarde 2:00pm - 10:00pm')], max_length=50, null=True),
        ),
    ]
