# Generated by Django 4.2 on 2026-06-07 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_alter_usuario_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='exportacion',
        ),
        migrations.AddField(
            model_name='exportacion',
            name='lote',
            field=models.ForeignKey(blank=True, db_column='lote_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.lote'),
        ),
        migrations.CreateModel(
            name='HistorialCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField(blank=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Enviado', 'Enviado'), ('Error', 'Error')], max_length=20)),
                ('error_detalle', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.empleado')),
            ],
        ),
    ]
