# Generated by Django 4.2 on 2026-06-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_remove_lote_exportacion_exportacion_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotacionturno',
            name='generado_automaticamente',
            field=models.BooleanField(default=False),
        ),
    ]
